# Generated by Django 5.2.8 on 2025-11-25 20:59 
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    initial = True 
 
    dependencies = [ 
    ] 
 
    operations = [ 
        migrations.CreateModel( 
            name='user', 
            fields=[ 
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), 
                ('username', models.CharField(max_length=200)), 
                ('password', models.CharField(max_length=200)), 
                ('creat_at', models.DateTimeField(auto_now_add=True)), 
                ('last_login', models.DateTimeField(blank=True, null=True)), 
            ], 
        ), 
    ] 
 