# Generated by Django 5.2.8 on 2025-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creat_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
