# Generated by Django 5.2.8 on 2025-11-20 11:20 
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0002_alter_post_creat_at'), 
    ] 
 
    operations = [ 
        migrations.AddField( 
            model_name='post', 
            name='image', 
            field=models.CharField(default='img2.jpg', max_length=255), 
            preserve_default=False, 
        ), 
    ] 
 