# Generated by Django 5.2.8 on 2025-11-20 11:20 
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0003_post_image'), 
    ] 
 
    operations = [ 
        migrations.AlterField( 
            model_name='post', 
            name='image', 
            field=models.CharField(blank=True, max_length=255, null=True), 
        ), 
    ] 
 