 # Generated by Django 5.2.8 on 2025-11-20 11:22
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0004_alter_post_image'), 
    ] 
 
    operations = [ 
        migrations.AlterField( 
            model_name='post', 
            name='image', 
            field=models.CharField(default='default.jpg', max_length=255), 
            preserve_default=False, 
        ), 
    ] 
 