# Generated by Django 5.2.8 on 2025-11-23 22:26 
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0005_alter_post_image'), 
    ] 
 
    operations = [ 
        migrations.RenameField( 
            model_name='post', 
            old_name='creat_at', 
            new_name='created_at', 
        ), 
        migrations.AlterField( 
            model_name='post', 
            name='image', 
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'), 
        ), 
    ] 
 