# Generated by Django 5.2.8 on 2025-11-23 22:29 
 
from django.db import migrations 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0006_rename_creat_at_post_created_at_alter_post_image'), 
    ] 
 
    operations = [ 
        migrations.RenameField( 
            model_name='post', 
            old_name='created_at', 
            new_name='creat_at', 
        ), 
        migrations.RemoveField( 
            model_name='post', 
            name='image', 
        ), 
    ] 
 