# Generated by Django 5.2.8 on 2025-11-26 11:12 
 
from django.db import migrations, models 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0007_rename_created_at_post_creat_at_remove_post_image'), 
    ] 
 
    operations = [ 
        migrations.AddField( 
            model_name='post', 
            name='images', 
            field=models.ImageField(blank=True, null=True, upload_to='posts'), 
        ), 
    ] 
 