# Generated by Django 5.2.8 on 2025-11-26 12:36 
 
from django.db import migrations 
 
 
class Migration(migrations.Migration): 
 
    dependencies = [ 
        ('blog', '0008_post_images'), 
    ] 
 
    operations = [ 
        migrations.RenameField( 
            model_name='post', 
            old_name='images', 
            new_name='image', 
        ), 
    ] 
 